# Generated by Django 5.2.17 on 2026-09-29 22:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='número')),
                ('idempotency_key', models.CharField(max_length=100, unique=True, verbose_name='chave de idempotência')),
                ('customer_name', models.CharField(max_length=200, verbose_name='cliente')),
                ('customer_document', models.CharField(max_length=14, verbose_name='CPF/CNPJ do cliente')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('invoiced', 'Faturado'), ('cancelled', 'Cancelado')], default='open', max_length=20, verbose_name='situação')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='total')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='erp_order_total_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preço unitário')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='erp_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='erp_item_unit_price_non_negative')],
            },
        ),
    ]
