# Generated by Django 5.2.17 on 2026-09-29 22:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Informe apenas os dígitos do CPF (11) ou do CNPJ (14).', regex='^(\\d{11}|\\d{14})$')], verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualification', 'Qualificação'), ('proposal', 'Proposta'), ('negotiation', 'Negociação'), ('won', 'Ganho'), ('lost', 'Perdido')], db_index=True, default='lead', max_length=20, verbose_name='estágio')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='previsão de fechamento')),
                ('lost_reason', models.TextField(blank=True, verbose_name='motivo da perda')),
                ('erp_order_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='pedido no ERP')),
                ('converted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='convertida em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.customer', verbose_name='cliente')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'oportunidade',
                'verbose_name_plural': 'oportunidades',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityStageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('lead', 'Lead'), ('qualification', 'Qualificação'), ('proposal', 'Proposta'), ('negotiation', 'Negociação'), ('won', 'Ganho'), ('lost', 'Perdido')], max_length=20, verbose_name='de')),
                ('to_stage', models.CharField(choices=[('lead', 'Lead'), ('qualification', 'Qualificação'), ('proposal', 'Proposta'), ('negotiation', 'Negociação'), ('won', 'Ganho'), ('lost', 'Perdido')], max_length=20, verbose_name='para')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='alterado em')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_changes', to='crm.opportunity', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'mudança de estágio',
                'verbose_name_plural': 'mudanças de estágio',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner', 'stage'], name='crm_opportu_owner_i_99a97c_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='crm_opportunity_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('erp_order_number__isnull', True), ('stage', 'won'), _connector='OR'), name='crm_opportunity_converted_only_when_won'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('converted_at__isnull', True), ('erp_order_number__isnull', True)), models.Q(('converted_at__isnull', False), ('erp_order_number__isnull', False)), _connector='OR'), name='crm_opportunity_conversion_fields_together'),
        ),
    ]
